src/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from .views import *

router = routers.DefaultRouter()

urlpatterns = [
    url(r'^v1/api-login', ObtainAuthToken.as_view()),
    url(r'^v1/quiickler/login', ObtainAuthTokenQuiickler.as_view()),
    url(r'^v1/quiickler/$', 'api.views.quiickler'),
    url(r'^v1/quiickler/(?P<pk>[0-9]+)/$', 'api.views.quiicklerElemento'),
    url(r'^v1/quiickler/disponibles/(-?\d+(?:\.\d+)?)/(-?\d+(?:\.\d+)?)/$', 'api.views.QuiicklersHaversine'),
    url(r'^v1/quiickler/historial/$', 'api.views.QuiicklerServicios'),
    url(r'^v1/servicio/express/$', 'api.views.servicioExpress'),
    url(r'^v1/servicio/programado/$', 'api.views.servicioProgramado'),
    url(r'^v1/servicio/sinrespuesta/(?P<pk>[0-9]+)/$', 'api.views.matarServicio'),
    url(r'^v1/servicio/confirmar/(?P<pk>[0-9]+)/$', 'api.views.confirmarServicio'),
    url(r'^v1/servicio/rechazar/(?P<pk>[0-9]+)/$', 'api.views.rechazarServicio'),
    url(r'^v1/servicio/(?P<pk>[0-9]+)/$', 'api.views.servicioElemento'),
    url(r'^v1/servicio/historial/$', 'api.views.misServicios'),
    #url(r'^v1/pedidos/$', 'api.views.pedidos'),
    url(r'^v1/servicio/finalizar/(?P<pk>[0-9]+)/$', 'api.views.servicioFinalizado'),
    url(r'^v1/evaluaciones/$', 'api.views.evaluaciones'),
    url(r'^v1/productos/$', 'api.views.productos'),
    url(r'^v1/productos/(?P<pk>[0-9]+)/$', 'api.views.producto'),
    url(r'^v1/tipos/$', 'api.views.tipos'),
    url(r'^v1/tipos/(?P<pk>[0-9]+)/$', 'api.views.tipo'),
    url(r'^v1/marcas/$', 'api.views.marcas'),
    url(r'^v1/marcas/(?P<pk>[0-9]+)/$', 'api.views.marca'),
    url(r'^v1/usuarios/detalle/', 'api.views.detalleUser'),
    url(r'^v1/usuarios/registrar', 'api.views.createUser'),
    url(r'^v1/usuarios/actualizar', 'api.views.actualizarDatos'),
    url(r'^v1/usuarios/direccion/$', 'api.views.direcciones'),
    url(r'^v1/usuarios/direccion/(?P<pk>[0-9]+)/$', 'api.views.direccion'),
    url(r'^v1/usuarios/recuperarpassword', 'api.views.olvidePassword'),
    url(r'^v1/usuarios/imagen/', 'api.views.cambiarImagenUsuario'),
    url(r'^v1/notificacion/registrar/android/', 'api.views.registrarAndroid'),
    url(r'^v1/', include(router.urls)),
]

src/dashboard/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.admin.views.decorators import staff_member_required


from .views import *

urlpatterns = [

    url(r'^info/$', staff_member_required(DashboardView.as_view()), name="dash"),
    url(r'^$', RedirectView.as_view(url='info/')),
    url(r'^usuarios/$', UserList.as_view(), name="usuarios_list"),
    url(r'^usuarios/toexcel/$', 'dashboard.views.UserEmailtoExcel', name="usuarios_email_to_excel"),
    #url(r'^estadisticas/$', EstadisticaView.as_view(), name="estadistica"),
    url(r'^productos/$', ProductoList.as_view(), name="productos_list"),
    url(r'^productos/crear/$', CreateProductoView.as_view(), name="productos_crear"),
    url(r'^productos/editar/(?P<pk>[0-9]+)/$', ProductoUpdate.as_view(), name='producto_editar'),
    url(r'^productos/tipos/$', TipoList.as_view(), name='tipo_list'),
    url(r'^productos/tipos/crear/$', TipoCreate.as_view(), name='tipo_crear'),
    url(r'^productos/tipos/editar/(?P<pk>[0-9]+)/$', TipoUpdate.as_view(), name='tipo_editar'),
    url(r'^productos/marcas/$', MarcaList.as_view(), name='marca_list'),
    url(r'^productos/marcas/crear/$', MarcaCreate.as_view(), name='marca_crear'),
    url(r'^productos/marcas/editar/(?P<pk>[0-9]+)/$', MarcaUpdate.as_view(), name='marca_editar'),
    url(r'^servicios/$', ServicioList.as_view(), name='servicios_list'),
    url(r'^servicios/(?P<pk>[0-9]+)/$', ServicioDetailView.as_view(), name='servicio-detail'),
    url(r'^pagos/$', RedirectView.as_view(url='sincancelar/')),
    url(r'^pagos/registrar/(?P<pk>[0-9]+)/$', 'dashboard.views.RegistrarPago', name='pagos_registrar'),
    url(r'^pagos/cancelados/$', PagoCanceladoList.as_view(), name="pagos_cancelados"),
    url(r'^pagos/sincancelar/$', PagoPorRecibirList.as_view(), name="pagos_sincancelar"),
    url(r'^ventas/$', VentaList.as_view(), name="ventas_list"),
    url(r'^ventas/(?P<pk>[0-9]+)/$', VentaDetailView.as_view(), name='venta-detail'),
    url(r'^quiicklers/$', QuiicklerList.as_view(), name="quiickler_list"),
    url(r'^quiicklers/mapaBusqueda/$', QuiicklerMapaBusqueda.as_view(), name="quiickler_mapa_busqueda"),
    url(r'^quiicklers/mapa/$', QuiicklerListMapa.as_view(), name="quiickler_mapa"),
    url(r'^quiicklers/crear/$', CreateQuiicklerView.as_view(), name="quiickler_create"),
    url(r'^quiicklers/edit/(?P<quiickler_pk>\d+)/$', EditQuiicklerView.as_view(), name='quiickler_edit'),
    url(r'^quiicklers/eliminar/(?P<pk>\d+)/$', 'dashboard.views.BorrarQuiickler', name='quiickler_eliminar'),

]

src/quiickly/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import api.urls
import dashboard.urls
import web.urls
from . import views

urlpatterns = [
    url(r'^$', views.LandingPage.as_view(), name='home'),
    url(r'^', include(web.urls, namespace='web')),
    url(r'^', include('password_reset.urls')),
    url(r'^dashboard/', include(dashboard.urls, namespace='dashboard')),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^acerca/$', views.AcercaPage.as_view(), name='acerca'),
    url(r'^api/', include(api.urls)),
    # url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^quiickly-admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dashboard/forms.py
from __future__ import unicode_literals
from django import forms
from django.contrib.auth import get_user_model
from .models import *

User = get_user_model()


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'name', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'name']


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        exclude = ['created', 'modified']


class QuiicklerForm(forms.ModelForm):

    class Meta:
        model = Quiickler
        exclude = ['user', 'created', 'modified', 'longitud', 'latitud']


class TipoForm(forms.ModelForm):

    class Meta:
        model = Tipo
        fields = ['tipo', ]


class MarcaForm(forms.ModelForm):

    class Meta:
        model = Marca
        fields = ['nombre', ]

src/dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.views.generic import ListView, View, TemplateView
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.detail import DetailView
from .models import *
from .forms import *
from servicios.models import Pago, Evaluacion, Venta, Servicio
import datetime
import dateutil
from django.db.models import Sum
import qsstats
from toexcel import queryset_to_workbook


User = get_user_model()


@login_required
def BorrarQuiickler(request, pk):
    """
    Detalle de un tipo de condon.
    """
    try:
        q = Quiickler.objects.get(pk=pk)
    except Quiickler.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        print q.user.is_active
        q.user.is_active = False
        q.estado = False
        q.user.save()
        q.save()
        return HttpResponseRedirect(reverse('dashboard:quiickler_list'))


class ProductoList(ListView):
    model = Producto
    template_name = 'dashboard/productos_list.html'

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(ProductoList, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ProductoList, self).get_context_data(**kwargs)
        # Add in the publisher
        disponibles = 0
        productos = Producto.objects.all()
        for p in productos:
            disponibles += p.cantidad

        context['disponibles'] = disponibles
        return context


class PagoCanceladoList(ListView):
    model = Pago
    template_name = 'dashboard/pagos_cancelados.html'

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(PagoCanceladoList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Pago.objects.all().filter(estado=True)
        return queryset


class PagoPorRecibirList(ListView):
    model = Pago
    template_name = 'dashboard/pagos_recibir.html'

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(PagoPorRecibirList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Pago.objects.all().filter(estado=False)
        return queryset


@login_required
def RegistrarPago(request, pk):
    """
    Registrar pago recibido.
    """
    try:
        p = Pago.objects.get(pk=pk)
    except Pago.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        if not p.estado:
            p.estado = True
            p.save()
        return HttpResponseRedirect(reverse('dashboard:pagos_sincancelar'))


class UserList(ListView):
    model = User
    template_name = 'dashboard/usuarios_list.html'

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(UserList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = User.objects.all().filter(quiickler=None)
        return queryset


class QuiicklerList(ListView):
    model = Quiickler

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(QuiicklerList, self).dispatch(request, *args, **kwargs)


class QuiicklerListMapa(ListView):
    model = Quiickler
    template_name = 'dashboard/quiickler_mapa.html'

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(QuiicklerListMapa, self).dispatch(request, *args, **kwargs)


class QuiicklerMapaBusqueda(ListView):
    model = RegistroBusqueda
    template_name = 'dashboard/quiickler_mapa_busqueda.html'

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(QuiicklerMapaBusqueda, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(QuiicklerMapaBusqueda, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['quiickler_list'] = Quiickler.objects.all()
        return context


class CreateQuiicklerView(View):

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(CreateQuiicklerView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = UserForm()
        form_q = QuiicklerForm()
        return render(
            request, "dashboard/create_quiickler.html",
            {"user_form": form, "q_form": form_q}
        )

    def post(self, request, *args, **kwargs):
        form_user = UserForm(request.POST)
        form_q = QuiicklerForm(request.POST, request.FILES)

        if form_q.is_valid() and form_user.is_valid():
            user = form_user.save(commit=False)
            user.set_password(user.password)
            user.save()
            q = form_q.save(commit=False)
            q.user = user
            q.save()
            return HttpResponseRedirect(reverse('dashboard:quiickler_list'))

        else:
            print "no es valido"
            return render(
                request, "dashboard/create_quiickler.html",
                {"user_form": form_user, "q_form": form_q}
            )


class CreateProductoView(View):

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(CreateProductoView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = ProductoForm()
        return render(
            request, "dashboard/create_producto.html",
            {"producto_form": form}
        )

    def post(self, request, *args, **kwargs):
        form = ProductoForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('dashboard:productos_list'))

        else:
            return render(
                request, "dashboard/create_producto.html",
                {"producto_form": form}
            )


class ProductoUpdate(UpdateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'dashboard/edit_producto.html'

    def get_success_url(self):
        messages.success(self.request, 'El producto fue actualizado.')
        return reverse('dashboard:producto_editar', kwargs={'pk': self.object.id})


class TipoCreate(CreateView):
    model = Tipo
    fields = ['tipo']
    success_url = reverse_lazy('dashboard:tipo_list')


class TipoList(ListView):
    model = Tipo
    template_name = 'dashboard/tipo_list.html'

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(TipoList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Tipo.objects.all()
        return queryset


class TipoUpdate(UpdateView):
    model = Tipo
    fields = ['tipo']
    template_name = 'dashboard/edit_tipo.html'

    def get_success_url(self):
        messages.success(self.request, 'El tipo fue actualizado.')
        return reverse('dashboard:tipo_editar', kwargs={'pk': self.object.id})


class MarcaCreate(CreateView):
    model = Marca
    fields = ['nombre']
    success_url = reverse_lazy('dashboard:marca_list')


class MarcaUpdate(UpdateView):
    model = Marca
    fields = ['nombre']
    template_name = 'dashboard/edit_marca.html'

    def get_success_url(self):
        messages.success(self.request, 'La marca fue actualizada.')
        return reverse('dashboard:marca_editar', kwargs={'pk': self.object.id})


class MarcaList(ListView):
    model = Marca
    template_name = 'dashboard/marca_list.html'

    #solo podra acceder si ha iniciado session
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise Http404("Esta pagina no existe!.")
        return super(MarcaList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Marca.objects.all()
        return queryset


class EditQuiicklerView(View):

src/dashboard/templates/dashboard/pagos_cancelados.html
{% extends 'dashboard/dash_base.html' %}
{% load staticfiles %}
{% block block_content %}
    <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Pagos
            <small>Informacion</small>
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Pagos cancelados</h3>
                            

                  <div class="box-tools pull-right">
	                
	              </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="qlist" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Quiickler</th>
                        <th>Servicio</th>
                        <th>Fecha</th>
                        <th>Usuario</th>
                        <th>Direccion</th>
                        <th>Total</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for p in object_list %}
                    	<tr>
	                      <th>{{p.quiickler.nombre}}</th>
                        <th><a href="{% url 'dashboard:servicio-detail' p.servicio.id %}">{{p.servicio.id}}</a></th>
                        <th>{{ p.servicio.created|date:'Y/m/d H:i' }}</th>
                        <th>{{ p.servicio.user.email }}</th>
                        <th>{{ p.servicio.direccion.direccion }}</th>
                        <th>{{ p.servicio.total }}</th>
                        <th></th>

                        </tr>
                    {% empty %}
                     <tr>
                       <th>No se encontraron pagos cancelados</th>
                        <th></th>
                       <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                       
                     </tr>

                    {% endfor %}

                      
                      
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Quiickler</th>
                        <th>Servicio</th>
                        <th>Fecha</th>
                        <th>Usuario</th>
                        <th>Direccion</th>
                        <th>Total</th>
                        <th></th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
{% endblock block_content %}

 {% block js %}
        <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>

    <script>
      $(function () {
        $("#qlist").DataTable();
    });
    </script>
 {% endblock js %}

src/dashboard/templates/dashboard/pagos_recibir.html
{% extends 'dashboard/dash_base.html' %}
{% load staticfiles %}
{% block block_content %}
    <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Pagos
            <small>Informacion</small>
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Pagos por recibir</h3>
                            

                  <div class="box-tools pull-right">
	                
	              </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="qlist" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Quiickler</th>
                        <th>Servicio</th>
                        <th>Fecha</th>
                        <th>Usuario</th>
                        <th>Direccion</th>
                        <th>Total</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for p in object_list %}
                    	<tr>
	                      <th>{{p.quiickler.nombre}}</th>
                        <th>{{p.servicio.id }}</th>
                        <th>{{ p.servicio.created|date:'Y/m/d H:i' }}</th>
                        <th>{{ p.servicio.user.email }}</th>
                        <th>{{ p.servicio.direccion.direccion }}</th>
                        <th>{{ p.servicio.total }}</th>
                        <th> <a href="{% url 'dashboard:pagos_registrar' p.pk %}" class="btn btn-sm btn-success"> Registrar pago</a></th>

                        </tr>
                    {% empty %}
                     <tr>
                       <th>No se encontraron pagos por recibir</th>
                        <th></th>
                       <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                       
                     </tr>

                    {% endfor %}

                      
                      
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Quiickler</th>
                        <th>Pedido</th>
                        <th>Fecha</th>
                        <th>Usuario</th>
                        <th>Direccion</th>
                        <th>Total</th>
                        <th></th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
{% endblock block_content %}

 {% block js %}
        <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>

    <script>
      $(function () {
        $("#qlist").DataTable();
    });
    </script>
 {% endblock js %}

src/dashboard/templates/dashboard/quiickler_list.html
{% extends 'dashboard/dash_base.html' %}
{% load staticfiles %}
{% block block_content %}
    <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Quiicklers
            <small>Informacion</small>
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Lista de Quiicklers</h3>
                  <div class="box-tools pull-right">
	                <a href="{% url 'dashboard:quiickler_create' %}" class="btn btn-box-tool"><i class="fa fa-plus"></i></a>
	              </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="qlist" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Correo</th>
                        <th>N. Servicios</th>
                        <th>Placa</th>
                        <th>Direccion</th>
                        <th>Telefono</th>
                        <th>Estado </th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for q in object_list %}
                    	<tr {% if not q.user.is_active %}
                          style="border: 3px solid #dd4b39 !important;"
                      
                      {% endif %}>
	                        <td><a href="{% url 'dashboard:quiickler_edit' q.pk %}">{{q.user.email}}</a></td>
	                        <td> {{ q.servicio_set.count }}</td>
	                        <td>{{ q.placa }}</td>
	                        <td>{{ q.direccion }} </td>
	                        <td> 
	                        {% if q.numero %}
	                        	{{ q.numero }} 
	                        {% else %}
	                            No tiene numero
	                        
	                        {% endif %}
	                        </td>
	                        <td> {% if q.estado %}
	                            <i class="fa fa-circle text-success"></i> Disponible
	                        {% else %}
	                        	<i class="fa fa-circle text-danger"></i> No Disponible
	                        {% endif %}</td>
                          <td>
                          {% if q.user.is_active %}

                              
                          <a href="{% url 'dashboard:quiickler_eliminar' q.pk %}" class="btn btn-sm btn-danger">Desactivar cuenta</a>
                          {% else %}
                              Cuenta desactivada
                          {% endif %}</td>

                        </tr>
                    {% empty %}
                     <tr>
                       <td>No se encontraron Quiicklers en la base de datos!.</td>
                       <td></td>
                       <td></td>
                       <td></td>
                       <td></td>
                       <td></td>
                       <td></td>
                     </tr>

                    {% endfor %}

                      
                      
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Correo</th>
                        <th>N. Servicios</th>
                        <th>Placa</th>
                        <th>Direccion</th>
                        <th>Telefono</th>
                        <th>Estado </th>
                        <th></th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
{% endblock block_content %}

 {% block js %}
        <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>

    <script>
      $(function () {
        $("#qlist").DataTable();
    });
    </script>
 {% endblock js %}

src/dashboard/templates/dashboard/usuarios_list.html
{% extends 'dashboard/dash_base.html' %}
{% load staticfiles %}
{% block block_content %}
    <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Usuarios
            <small>Informacion</small>
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title"><span>Cantidad: </span><strong>{{ object_list.count }}</strong></h3>
                  
                  <div class="box-tools pull-right">
	                 <a href="{% url 'dashboard:usuarios_email_to_excel' %}"><i class="fa fa-file-excel-o"></i> Exportar a Excel(Email)</a>
	              </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="qlist" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Fecha de registro</th>
                        <th>Correo</th>
                        <th>N. pedidos</th>
                        <th>Activo </th>
                        <th>Ultima sesion</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for u in object_list %}
                    	<tr>
                          <td> {{ u.date_joined|date:"Y/m/d" }}</td>
	                        <td>{{u.email}}</td>
	                        <td> {{ u.pedidos.count }}</td>
	                        <td> {% if u.is_active %}
	                            <i class="fa fa-circle text-success"></i> 
	                        {% else %}
	                        	<i class="fa fa-circle text-danger"></i>
	                        {% endif %}</td>
                          <td>
                          {{ u.last_login|timesince}}
                          </td>
                          <td> </td>

                        </tr>
                    {% empty %}
                     <tr>
                       <td>No se encontraron Usuraios en la base de datos!.</td>
                       <td></td>
                       <td></td>
                       <td></td>
                       <td></td>
                       <td></td>
                       
                     </tr>

                    {% endfor %}

                      
                      
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Fecha de registro</th>
                        <th>Correo</th>
                        <th>N. pedidos</th>
                        <th>Activo </th>
                        <th> Ultima sesion </th>
                        <th></th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
{% endblock block_content %}

 {% block js %}
        <!-- DataTables -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>

    <script>
      $(function () {
        $("#qlist").DataTable();
    });
    </script>
 {% endblock js %}